
[package]
name = "etx-rs"
version = "2.9.0"
edition = "2021"

[lib]
name = "rs"
crate-type = ["staticlib"]
test = false
bench = false

[build-dependencies]
cbindgen = "0.20.0"
bindgen = "0.53.1"

[dependencies]
cty = "0.2"
