---
name: Run tests and package firmware
on:
  push:
    branches:
    - '2.4'
  pull_request:
    branches:
    - '2.4'

jobs:
  metadata:
    name: Store metadata
    runs-on: ubuntu-latest
    steps: 
    - name: Check out the repo
      uses: actions/checkout@v2 
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Package common files
      uses: 'actions/upload-artifact@v2'
      with:
        name: "edgex-firmware-${{ steps.extract_branch.outputs.branch }}"
        path: |
          fw.json
          LICENSE
          README.md

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - T12
          - T16
          - T8
          - TLITE
          - TX12
          - TX16S
          - X10
          - X12S
          - X7
          - X9DP
          - X9DP2019
          - X9LITE
          - XLITE
    container:
      image: ghcr.io/edgetx/edgetx-commit-tests
      volumes:
        - ${{ github.workspace }}:/src
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # - name: Fetch tags
      #   run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Test ${{ matrix.target }}
        env:
          FLAVOR: ${{ matrix.target }}
        run: |
          echo "Running commit tests"
          ./tools/commit-tests.sh

      - name: Build ${{ matrix.target }}
        env:
          FLAVOR: ${{ matrix.target }}
        run: |
          echo "Running firmware build"
          ./tools/build-gh.sh

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Package firmware ${{ matrix.target }}
        uses: 'actions/upload-artifact@v2'
        with:
          name: "edgex-firmware-${{ steps.extract_branch.outputs.branch }}"
          path: "${{ github.workspace }}/*.bin"
          retention-days: 15
          if-no-files-found: error
