name: Linux Companion

on:
  push:
    branches:
      - '2.6'
      - '2.7'
      - '2.8'
      - '2.9'
      - 'main'
    tags:
      - v*
    paths:
      - '.github/workflows/linux_cpn.yml'
      - 'companion/**'
      - 'tools/build-companion.sh'

  pull_request:
    branches:
      - '2.6'
      - '2.7'
      - '2.8'
      - '2.9'
      - 'main'
    paths:
      - '.github/workflows/linux_cpn.yml'
      - 'companion/**'
      - 'tools/build-companion.sh'

  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/edgetx/edgetx-dev:2.9.1
      volumes:
        - ${{ github.workspace }}:/src

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
          rm /etc/apt/sources.list.d/kitware.list && apt-get update
          apt-get install --yes --no-install-recommends dfu-util libssl-dev awesome && \
          rm -rf /var/lib/apt/lists/*
          LIBUSB1_ROOT_DIR=/usr/lib/x86_64-linux-gnu && \
          LIBSSL1_ROOT_DIR=/usr/lib/x86_64-linux-gnu && \
          mkdir output && \
          tools/build-companion.sh "$(pwd)" "$(pwd)/output/"

      - name: Compose release filename
        # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
        run: echo "artifact_name=edgetx-cpn-linux-${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "${{ env.artifact_name }}"
          path:  ${{github.workspace}}/output
          retention-days: 15
